### ISSUE TITLE
gatk issue about sam/bam

### ISSUE THREAD

**Issue by MengZhang2019** [marqueda/SFS-scripts#2]
Hello,
I attend you push a question about the bam/sam file's format. 
I have the same question like you:
"""
WARNING	2019-11-26 09:16:33	ValidateSamFile	NM validation cannot be performed without the reference. All other validations will still occur.
ERROR	2019-11-26 09:16:33	ValidateSamFile	Cannot add sequence that already exists in SAMSequenceDictionary: NC_013791.2
[Tue Nov 26 09:16:33 CST 2019] picard.sam.ValidateSamFile done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2115502080
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Tool returned:
-1
"""
How did you solve the issue, can you help me.
or give me some advises.
Thank you very much.

**Comment by marqueda** [comment]
Dear MengZhang2019,

I don't understand how this error message is related to any of the SFS-scripts in my repository. Could you please give more detail which of my scripts led to this error message?

If the problem is related to GATK as you write, or to Picard, as the error message suggests, please contact the GATK / Picard forums.

Best regards,
David

**Comment by MengZhang2019** [comment]
I missed it.
Sorry

**Comment by MengZhang2019** [comment]
I missed it.
Sorry.
Thanks for your reply
